#!/bin/bash
if [ $# -eq 0 ]; then
    echo "Usage: ./server.sh [ start | install ]"
    exit 1
fi

if [ $1 == "start" ]; then
    echo "Starting server..."
    env/bin/python -m gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 --bind 0.0.0.0:8000 app:app
elif [ $1 == "install" ]; then
    env/bin/python -m pip install -r requirements.txt
else
    echo "Invalid argument"
fi